name: CI/CD - CarApp

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/car-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/car-app:${{ github.sha }}

  deploy_to_ec2:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Write SSH key
        run: |
          umask 077
          cat > key.pem <<'KEY'
          ${{ secrets.EC2_SSH_KEY }}
          KEY
          chmod 600 key.pem

      - name: Deploy on EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          SHA:  ${{ github.sha }}
          DHU:  ${{ secrets.DOCKERHUB_USERNAME }}
          DHT:  ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem "$USER@$HOST" \
            bash -s -- "$SHA" "$DHU" "$DHT" <<'REMOTE'
          set -e
          SHA="$1"; DHU="$2"; DHT="$3"
          cd /opt/carapp

          # .env’de çalışan imaj etiketini commit SHA yap
          if grep -q '^CARAPP_TAG=' .env; then
            sudo sed -i "s/^CARAPP_TAG=.*/CARAPP_TAG=${SHA}/" .env
          else
            echo "CARAPP_TAG=${SHA}" | sudo tee -a .env
          fi

          # Docker Hub’a giriş ve sadece web servisini yenile
          echo "${DHT}" | sudo docker login -u "${DHU}" --password-stdin
          sudo docker compose pull web
          sudo docker compose up -d --no-deps web
          REMOTE
